# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mazhuang.org
date_format: "ordinal"
title: 九九叔
subtitle: 九九叔的github之家
description: 九九叔的github之家
keywords: 九九叔, JiuJiuShu, jjslogin, JiuJiuShu
favicon: /favicon.ico
timezone: Asia/Shenzhen
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: JiuJiuShu
organization: OPPO, Inc.
organization_url: http://www.oppo.com
github_username: wenfengtou
location: Shenzhen, China
email: qianmayi@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
